### ISSUE TITLE
Theme using the terminal background.

### ISSUE THREAD

**Issue by RedsonBr140** [nocksock/bloop-vim#1]
I don't know if it was the expected behaviour of the theme, but it's using the terminal background instead of the blue background in the README.md screenshot.
![](https://0x0.st/oPeP.png)
> Info: Kitty and neovim-0.6.1

**Comment by nocksock** [comment]
Hi!

The theme is still work in progress, but yes this _was_ intentional. This way one can still use the terminal's transparency features - if available. I'll update the theme later with current and slightly adjusted colors and provide an option to explicitly turn the background off instead.

I might also provide settings for kitty (and in my case Alacritty). I'll let you know when that happened. 

Thanks for checking the theme out! 
Didn't expect people to find it in its current state. :)

**Comment by nocksock** [comment]
@RedsonBr140 I added an option to disable the background color, and now it's set by default.
